package com.where.domain;

//import com.where.hibernate.Station;
// Generated 24-Aug-2008 23:56:26 by Hibernate Tools 3.2.1.GA


/**
 * TflStationCodes generated by hbm2java
 */
public class TflStationCode implements java.io.Serializable {

  private final Station station;
  private final String code;
  private final String line;

    public TflStationCode(Station station, String code, String line) {
    this.station = station;
    this.code = code;
    this.line = line;
  }

  public Station getStation() {
    return this.station;
  }

  public String getCode() {
    return this.code;
  }

  public String getLine() {
    return this.line;
  }

}