package com.where.dao.hibernate;
// Generated 24-Aug-2008 23:56:26 by Hibernate Tools 3.2.1.GA



/**
 * Branches generated by hbm2java
 */
public class Branch implements java.io.Serializable {


     private Integer id;
     private String name;
     private String line;

    public Branch() {
    }

    public Branch(String name, String line) {
       this.name = name;
       this.line = line;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLine() {
        return this.line;
    }
    
    public void setLine(String line) {
        this.line = line;
    }




}


