package com.where.dao.hibernate;
// Generated 24-Aug-2008 23:56:26 by Hibernate Tools 3.2.1.GA



/**
 * StationsTest generated by hbm2java
 */
public class StationsTest  implements java.io.Serializable {
     private Integer id;
     private String name;
     private String line;
     private String x;
     private String y;

    public StationsTest() {
    }

    public StationsTest(String name, String line, String x, String y) {
       this.name = name;
       this.line = line;
       this.x = x;
       this.y = y;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLine() {
        return this.line;
    }
    
    public void setLine(String line) {
        this.line = line;
    }
    public String getX() {
        return this.x;
    }
    
    public void setX(String x) {
        this.x = x;
    }
    public String getY() {
        return this.y;
    }
    
    public void setY(String y) {
        this.y = y;
    }




}


