package com.where.dao.pojo;
// Generated 24-Aug-2008 23:56:26 by Hibernate Tools 3.2.1.GA


/**
 * Stations generated by hbm2java
 */
public class Station implements java.io.Serializable {

  private final int id;
  private final String name;
  private final String line;
  private final double x;
  private final double y;

  public Station(int id, String name, String line, double x, double y) {
      this.id = id;
    this.name = name;
    this.line = line;
    this.x = x;
    this.y = y;
  }

  public Integer getId() {
    return this.id;
  }

  public String getName() {
    return this.name;
  }


  public String getLine() {
    return this.line;
  }



  public double getX() {
    return this.x;
  }



  public double getY() {
    return this.y;
  }

}