package com.where.hibernate;
// Generated 24-Aug-2008 23:56:26 by Hibernate Tools 3.2.1.GA


/**
 * TflStationCodes generated by hbm2java
 */
public class TflStationCode implements java.io.Serializable {

  private Integer id;
  private String stationId;
  private String code;
  private String line;

  public TflStationCode() {
  }

  public TflStationCode(String stationId, String code, String line) {
    this.stationId = stationId;
    this.code = code;
    this.line = line;
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getStationId() {
    return this.stationId;
  }

  public void setStationId(String stationId) {
    this.stationId = stationId;
  }

  public String getCode() {
    return this.code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String getLine() {
    return this.line;
  }

  public void setLine(String line) {
    this.line = line;
  }


}


