package com.where.domain;

import com.where.dao.hibernate.Station;
// Generated 24-Aug-2008 23:56:26 by Hibernate Tools 3.2.1.GA


/**
 * TflStationCodes generated by hbm2java
 */
public class TflStationCode implements java.io.Serializable {

  private final int id;
  private final Station stationId;
  private final String code;
  private final String line;

  public TflStationCode(int id, Station stationId, String code, String line) {
      this.id = id;
    this.stationId = stationId;
    this.code = code;
    this.line = line;
  }

  public Integer getId() {
    return this.id;
  }

  public Station getStationId() {
    return this.stationId;
  }

  public String getCode() {
    return this.code;
  }

  public String getLine() {
    return this.line;
  }

}